# Generated by Django 6.1 on 2026-09-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaaccount',
            name='selected_page_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
