# Generated by Django 5.2.17 on 2026-08-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('field_key', models.SlugField(max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Email', 'Email'), ('Phone', 'Phone'), ('Dropdown', 'Dropdown'), ('Multi Select', 'Multi Select'), ('Checkbox', 'Checkbox'), ('Date', 'Date'), ('Date & Time', 'Date & Time'), ('Currency', 'Currency'), ('URL', 'URL'), ('Long Text', 'Long Text')], default='Text', max_length=30)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of string options for Dropdown / Multi Select')),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='enquiries.enquiry')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_fields.customfielddefinition')),
            ],
            options={
                'unique_together': {('enquiry', 'field_definition')},
            },
        ),
    ]
