# Generated by Django 5.2.17 on 2026-08-08 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Enquiry', max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Closed', 'Closed'), ('Lost', 'Lost')], db_index=True, default='New', max_length=50)),
                ('source', models.CharField(choices=[('Meta Ads', 'Meta Ads'), ('Manual', 'Manual'), ('Bulk Upload', 'Bulk Upload'), ('Website', 'Website')], db_index=True, default='Manual', max_length=50)),
                ('campaign_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('ad_set_name', models.CharField(blank=True, default='', max_length=255)),
                ('ad_name', models.CharField(blank=True, default='', max_length=255)),
                ('instant_form_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('meta_lead_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('raw_form_data', models.JSONField(blank=True, default=dict)),
                ('notes_summary', models.TextField(blank=True, default='')),
                ('follow_up_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='contacts.contact')),
                ('primary_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_enquiries', to=settings.AUTH_USER_MODEL)),
                ('secondary_owners', models.ManyToManyField(blank=True, related_name='secondary_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('ENQUIRY_CREATED', 'Enquiry Created'), ('ASSIGNMENT_CHANGED', 'Assignment Changed'), ('STATUS_UPDATED', 'Status Updated'), ('CALL_LOGGED', 'Call Logged'), ('NOTE_ADDED', 'Note Added'), ('FOLLOWUP_SCHEDULED', 'Follow-up Scheduled'), ('FOLLOWUP_COMPLETED', 'Follow-up Completed'), ('ATTACHMENT_UPLOADED', 'Attachment Uploaded'), ('CONTACT_UPDATED', 'Contact Information Updated')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='enquiries.enquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('filters_config', models.JSONField(default=dict)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', 'name'],
            },
        ),
    ]
