# Generated by Django 6.1 on 2026-09-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='page_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='page_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
